name: Docker Cleanup

on:
  schedule:
    - cron: '00 0 * * *'
  workflow_dispatch:

concurrency:
  group: docker-cleanup-${{ github.repository }}
  cancel-in-progress: false

jobs:
  delete-old-images-main:
    name: Delete Old Images for Main Repo
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f
        with:
          dry-run: true
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
          delete-untagged: true
          validate: true
          token: ${{ github.token }}
          owner: ${{ github.repository_owner }}
          package: homebox
          use-regex: false
          exclude-tags: "latest,latest-rootless,main,main-rootless,nightly,nightly-rootless,*.*.*,0.*,0,*.*.*-rootless,0.*-rootless,0-rootless"
          older-than: 180 days

  delete-old-images-devcache:
    name: Delete Old Devcache Images
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f
        with:
          dry-run: false
          delete-untagged: true
          token: ${{ github.token }}
          owner: ${{ github.repository_owner }}
          package: homebox-devcache
          older-than: 90 days
